[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
thiserror = "2"

[build-dependencies]
lalrpop = "0.22.2"
